# Generated by Django 6.0 on 2025-12-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Обработано'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='processed_notes',
            field=models.TextField(blank=True, verbose_name='Заметки обработки'),
        ),
    ]
