# Generated by Django 6.0 on 2025-12-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание')),
                ('short_description', models.CharField(max_length=300, verbose_name='Краткое описание')),
                ('image', models.ImageField(upload_to='games/', verbose_name='Изображение')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата выхода')),
                ('developer', models.CharField(blank=True, max_length=100, verbose_name='Разработчик')),
                ('publisher', models.CharField(blank=True, max_length=100, verbose_name='Издатель')),
                ('genre', models.CharField(blank=True, choices=[('RPG', 'Ролевые'), ('ACTION', 'Экшен'), ('STRATEGY', 'Стратегии'), ('ADVENTURE', 'Приключения'), ('SIMULATION', 'Симуляторы'), ('SPORT', 'Спортивные')], max_length=20, verbose_name='Жанр')),
                ('platform', models.CharField(blank=True, max_length=100, verbose_name='Платформа')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['title'],
            },
        ),
    ]
