# Generated by Django 6.0 on 2025-12-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-created'], 'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AddField(
            model_name='game',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступно для покупки'),
        ),
        migrations.AddField(
            model_name='game',
            name='metacritic_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оценка Metacritic'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.CharField(max_length=100, verbose_name='Разработчик'),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('RPG', 'Ролевые'), ('ACTION', 'Экшен'), ('STRATEGY', 'Стратегии'), ('ADVENTURE', 'Приключения'), ('SIMULATION', 'Симуляторы'), ('SPORT', 'Спортивные'), ('INDIE', 'Инди'), ('HORROR', 'Хоррор')], max_length=20, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(upload_to='games/%Y/%m/%d/', verbose_name='Обложка игры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(default='PC', max_length=100, verbose_name='Платформа'),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='URL-адрес'),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название игры'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['title'], name='catalog_gam_title_cb1b3f_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['genre'], name='catalog_gam_genre_7affad_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['price'], name='catalog_gam_price_a78de4_idx'),
        ),
    ]
