import os
import django
from datetime import date
import random

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'game_catalog.settings')
django.setup()

from catalog.models import Game

def create_game(game_data):
    """Создает или обновляет игру"""
    game, created = Game.objects.update_or_create(
        title=game_data['title'],
        defaults=game_data
    )
    if created:
        print(f'✅ Добавлена: {game.title}')
    else:
        print(f'🔄 Обновлена: {game.title}')
    return game

# AAA игры (крупные студии, большие бюджеты)
aaa_games = [
    {
        'title': 'The Witcher 3: Wild Hunt',
        'slug': 'the-witcher-3-wild-hunt',
        'description': '«Ведьмак 3: Дикая Охота» — это сюжетная ролевая игра с открытым миром. Вы играете за профессионального охотника на чудовищ Геральта из Ривии. Вам предстоит отправиться в эпическое путешествие по густонаселенным землям, полным торговых городов, пиратских островов, опасных горных перевалов и заброшенных пещер.',
        'short_description': 'Эпическая RPG от CD Projekt RED с открытым миром',
        'price': 1999.99,
        'developer': 'CD Projekt RED',
        'publisher': 'CD Projekt',
        'genre': 'RPG',
        'platform': 'PC, PlayStation 4, Xbox One, Nintendo Switch',
        'metacritic_score': 93,
        'release_date': date(2015, 5, 19),
        'is_available': True,
    },
    {
        'title': 'Red Dead Redemption 2',
        'slug': 'red-dead-redemption-2',
        'description': 'Америка, 1899 год. Эпоха Дикого Запада подходит к концу. Банда Датча Ван дер Линде вынуждена пуститься в бега. На их счету ограбления в разных штатах, и федеральные агенты и лучшие в стране охотники за головами начинают охоту на членов банды.',
        'short_description': 'Эпический вестерн от создателей GTA V',
        'price': 3499.99,
        'developer': 'Rockstar Games',
        'publisher': 'Rockstar Games',
        'genre': 'ACTION',
        'platform': 'PC, PlayStation 4, Xbox One',
        'metacritic_score': 97,
        'release_date': date(2018, 10, 26),
        'is_available': True,
    },
    {
        'title': 'Cyberpunk 2077',
        'slug': 'cyberpunk-2077',
        'description': 'Cyberpunk 2077 — приключенческая ролевая игра, действие которой происходит в мегаполисе Найт-Сити, где власть, роскошь и модификации тела ценятся выше всего. Вы играете за V, наёмника в поисках уникального имплантата, который является ключом к бессмертию.',
        'short_description': 'Футуристическая RPG в открытом мире',
        'price': 2999.99,
        'developer': 'CD Projekt RED',
        'publisher': 'CD Projekt',
        'genre': 'RPG',
        'platform': 'PC, PlayStation 5, Xbox Series X/S',
        'metacritic_score': 86,
        'release_date': date(2020, 12, 10),
        'is_available': True,
    },
    {
        'title': 'Elden Ring',
        'slug': 'elden-ring',
        'description': 'Elden Ring — новая ролевая игра с фэнтезийным сеттингом, созданная в сотрудничестве Хидэтаки Миядзаки и Джорджа Р. Р. Мартина. Исследуйте мир Межземья, сражайтесь с могучими противниками и раскрывайте секреты древних богов.',
        'short_description': 'Эпическая dark fantasy RPG от FromSoftware',
        'price': 3499.99,
        'developer': 'FromSoftware',
        'publisher': 'Bandai Namco',
        'genre': 'RPG',
        'platform': 'PC, PlayStation 5, Xbox Series X/S',
        'metacritic_score': 96,
        'release_date': date(2022, 2, 25),
        'is_available': True,
    },
    {
        'title': 'God of War (2018)',
        'slug': 'god-of-war-2018',
        'description': 'Это совершенно новое начало. Живя как человек за пределами тени богов, Кратос должен адаптироваться к незнакомым землям, неожиданным угрозам и возможности стать отцом, снова. Вместе со своим сыном Атреем они отправляются в суровое путешествие по миру скандинавской мифологии.',
        'short_description': 'Переосмысление культовой серии в скандинавском сеттинге',
        'price': 2999.99,
        'developer': 'Santa Monica Studio',
        'publisher': 'Sony Interactive Entertainment',
        'genre': 'ACTION',
        'platform': 'PC, PlayStation 4, PlayStation 5',
        'metacritic_score': 94,
        'release_date': date(2018, 4, 20),
        'is_available': True,
    },
    {
        'title': 'The Last of Us Part II',
        'slug': 'the-last-of-us-part-ii',
        'description': 'Прошло пять лет после их опасного путешествия по постапокалиптическим США. Элли и Джоэл поселились в Джексоне, штат Вайоминг. Жизнь в процветающем сообществе выживших дала им мир и стабильность, несмотря на постоянную угрозу зараженных и других, более отчаянных выживших.',
        'short_description': 'Эмоциональный постапокалиптический экшен-приключение',
        'price': 3999.99,
        'developer': 'Naughty Dog',
        'publisher': 'Sony Interactive Entertainment',
        'genre': 'ACTION',
        'platform': 'PlayStation 4, PlayStation 5',
        'metacritic_score': 93,
        'release_date': date(2020, 6, 19),
        'is_available': True,
    },
    {
        'title': 'Grand Theft Auto V',
        'slug': 'grand-theft-auto-v',
        'description': 'Когда молодой уличный мошенник, отставной грабитель банков и психопат-преступник оказываются втянутыми в мир преступности и власти, они должны совершить серию опасных ограблений, чтобы выжить в жестоком мире, где они не могут доверять никому, даже друг другу.',
        'short_description': 'Культовая криминальная сага в открытом мире',
        'price': 1499.99,
        'developer': 'Rockstar North',
        'publisher': 'Rockstar Games',
        'genre': 'ACTION',
        'platform': 'PC, PlayStation 5, Xbox Series X/S, PlayStation 4, Xbox One',
        'metacritic_score': 97,
        'release_date': date(2013, 9, 17),
        'is_available': True,
    },
    {
        'title': 'Horizon Forbidden West',
        'slug': 'horizon-forbidden-west',
        'description': 'Отправляйтесь в захватывающее путешествие по опасному и великолепному Запретному Западу будущей Америки. Сражайтесь с огромными машинами и встретьтесь с новыми удивительными племенами, возвращаясь в мир, находящийся на грани краха.',
        'short_description': 'Приключение в постапокалиптическом мире с роботами-динозаврами',
        'price': 4499.99,
        'developer': 'Guerrilla Games',
        'publisher': 'Sony Interactive Entertainment',
        'genre': 'ACTION',
        'platform': 'PlayStation 5, PlayStation 4',
        'metacritic_score': 88,
        'release_date': date(2022, 2, 18),
        'is_available': True,
    },
    {
        'title': 'Assassin\'s Creed Valhalla',
        'slug': 'assassins-creed-valhalla',
        'description': 'Станьте Эйвором, легендарным викингом-воином, вынужденным покинуть Норвегию в поисках славы и новых земель в Англии IX века. Возглавьте набеги викингов с вашего длинного корабля, займите новые земли для своего клана и постройте новое поселение.',
        'short_description': 'Историческое приключение в мире викингов',
        'price': 2999.99,
        'developer': 'Ubisoft Montreal',
        'publisher': 'Ubisoft',
        'genre': 'ACTION',
        'platform': 'PC, PlayStation 5, Xbox Series X/S, PlayStation 4, Xbox One',
        'metacritic_score': 84,
        'release_date': date(2020, 11, 10),
        'is_available': True,
    },
    {
        'title': 'Call of Duty: Modern Warfare II',
        'slug': 'call-of-duty-modern-warfare-ii',
        'description': 'Call of Duty: Modern Warfare II ставит игроков в центр беспрецедентной глобальной угрозы, в которой появляется новая элитная оперативная группа под кодовым названием Task Force 141.',
        'short_description': 'Продолжение культового военного шутера',
        'price': 3999.99,
        'developer': 'Infinity Ward',
        'publisher': 'Activision',
        'genre': 'ACTION',
        'platform': 'PC, PlayStation 5, Xbox Series X/S, PlayStation 4, Xbox One',
        'metacritic_score': 77,
        'release_date': date(2022, 10, 28),
        'is_available': True,
    },
]

# AA игры (средние студии, хороший бюджет)
aa_games = [
    {
        'title': 'Hollow Knight',
        'slug': 'hollow-knight',
        'description': 'Погрузитесь в мир Hollow Knight! Epic приключение в стиле action-adventure через огромное разрушенное королевство насекомых и героев. Исследуйте извилистые пещеры, сражайтесь с испорченными существами и заводите друзей с причудливыми жуками.',
        'short_description': 'Культовая метроидвания с уникальным стилем',
        'price': 699.99,
        'developer': 'Team Cherry',
        'publisher': 'Team Cherry',
        'genre': 'ADVENTURE',
        'platform': 'PC, PlayStation 4, Xbox One, Nintendo Switch',
        'metacritic_score': 90,
        'release_date': date(2017, 2, 24),
        'is_available': True,
    },
    {
        'title': 'Dead Cells',
        'slug': 'dead-cells',
        'description': 'Dead Cells — это roguelike, метроидвания, разработанный и изданный Motion Twin. Игроки принимают контроль над массой клеток, которые захватывают тело мертвого заключенного в замке.',
        'short_description': 'Roguelike-метроидвания с пиксельной графикой',
        'price': 799.99,
        'developer': 'Motion Twin',
        'publisher': 'Motion Twin',
        'genre': 'ACTION',
        'platform': 'PC, PlayStation 4, Xbox One, Nintendo Switch, Android, iOS',
        'metacritic_score': 89,
        'release_date': date(2018, 8, 7),
        'is_available': True,
    },
    {
        'title': 'Hades',
        'slug': 'hades',
        'description': 'Вырвитесь из преисподней в этой roguelike-аркаде от создателей Bastion, Transistor и Pyre. Бросьте вызов богу мертвых, сражаясь с его армией из преисподней, используя силы и милости олимпийских богов.',
        'short_description': 'Roguelike с видом сверху и греческой мифологией',
        'price': 999.99,
        'developer': 'Supergiant Games',
        'publisher': 'Supergiant Games',
        'genre': 'ACTION',
        'platform': 'PC, PlayStation 5, Xbox Series X/S, Nintendo Switch',
        'metacritic_score': 93,
        'release_date': date(2020, 9, 17),
        'is_available': True,
    },
    {
        'title': 'Disco Elysium',
        'slug': 'disco-elysium',
        'description': 'Disco Elysium — это инновационная ролевая игра. Вы играете за следователя, который должен раскрыть дело о смерти в вымышленном городе Ревашоль. Исследуйте мир, допрашивайте персонажей и принимайте решения, которые формируют сюжет.',
        'short_description': 'Детективная RPG без боёв, только диалоги',
        'price': 1199.99,
        'developer': 'ZA/UM',
        'publisher': 'ZA/UM',
        'genre': 'RPG',
        'platform': 'PC, PlayStation 5, Xbox Series X/S, Nintendo Switch',
        'metacritic_score': 91,
        'release_date': date(2019, 10, 15),
        'is_available': True,
    },
    {
        'title': 'Subnautica',
        'slug': 'subnautica',
        'description': 'Разбившись на незнакомой планете-океане, единственный способ выжить — спуститься в глубины. Но странные существа скрываются в каждом тёмном уголке этого подводного мира.',
        'short_description': 'Выживание в подводном мире на чужой планете',
        'price': 899.99,
        'developer': 'Unknown Worlds Entertainment',
        'publisher': 'Unknown Worlds Entertainment',
        'genre': 'ADVENTURE',
        'platform': 'PC, PlayStation 4, Xbox One, Nintendo Switch',
        'metacritic_score': 87,
        'release_date': date(2018, 1, 23),
        'is_available': True,
    },
    {
        'title': 'Outer Wilds',
        'slug': 'outer-wilds',
        'description': 'Outer Wilds — это приключенческая игра с открытым миром, действие которой происходит в постоянно меняющейся солнечной системе, которая обречена на уничтожение в результате взрыва сверхновой звезды через 22 минуты.',
        'short_description': 'Исследование космоса в 22-минутном временном цикле',
        'price': 999.99,
        'developer': 'Mobius Digital',
        'publisher': 'Annapurna Interactive',
        'genre': 'ADVENTURE',
        'platform': 'PC, PlayStation 4, Xbox One, Nintendo Switch',
        'metacritic_score': 85,
        'release_date': date(2019, 5, 28),
        'is_available': True,
    },
    {
        'title': 'Celeste',
        'slug': 'celeste',
        'description': 'Помогите Мадлин пережить её внутренние демоны в её путешествии на вершину горы Селеста в этой сверхточный платформер от создателей TowerFall. Покоряйте сотни сложных площадок, исследуйте загадочные тайны горы.',
        'short_description': 'Сложный пиксельный платформер с глубоким сюжетом',
        'price': 599.99,
        'developer': 'Extremely OK Games',
        'publisher': 'Matt Makes Games',
        'genre': 'ADVENTURE',
        'platform': 'PC, PlayStation 4, Xbox One, Nintendo Switch',
        'metacritic_score': 92,
        'release_date': date(2018, 1, 25),
        'is_available': True,
    },
    {
        'title': 'Stardew Valley',
        'slug': 'stardew-valley',
        'description': 'Унаследовав старую ферму своего деда в долине Стардью, вы, вооружившись ветхими инструментами и небольшим количеством монет, решите начать новую жизнь. Сможете ли вы научиться жить за счёт земли и превратить эти заросшие поля в процветающий дом?',
        'short_description': 'Расслабляющая фермерская симуляция с RPG элементами',
        'price': 399.99,
        'developer': 'ConcernedApe',
        'publisher': 'ConcernedApe',
        'genre': 'SIMULATION',
        'platform': 'PC, PlayStation 4, Xbox One, Nintendo Switch, Android, iOS',
        'metacritic_score': 89,
        'release_date': date(2016, 2, 26),
        'is_available': True,
    },
    {
        'title': 'Factorio',
        'slug': 'factorio',
        'description': 'Факторио — это игра о строительстве и создании автоматизированных фабрик для производства все более сложных предметов на чужой планете. Вам нужно будет добывать ресурсы, исследовать технологии, строить инфраструктуру.',
        'short_description': 'Сложный симулятор автоматизированного производства',
        'price': 1299.99,
        'developer': 'Wube Software',
        'publisher': 'Wube Software',
        'genre': 'SIMULATION',
        'platform': 'PC, Nintendo Switch',
        'metacritic_score': 90,
        'release_date': date(2020, 8, 14),
        'is_available': True,
    },
    {
        'title': 'Deep Rock Galactic',
        'slug': 'deep-rock-galactic',
        'description': 'Deep Rock Galactic — это шутер от первого лица для 1-4 игроков, в котором вы играете за гномов-космических шахтеров. Работайте вместе, чтобы добывать полезные ископаемые, сражайтесь с враждебными инопланетными формами жизни.',
        'short_description': 'Кооперативный шутер про космических гномов-шахтеров',
        'price': 999.99,
        'developer': 'Ghost Ship Games',
        'publisher': 'Coffee Stain Publishing',
        'genre': 'ACTION',
        'platform': 'PC, PlayStation 5, Xbox Series X/S',
        'metacritic_score': 85,
        'release_date': date(2020, 5, 13),
        'is_available': True,
    },
]

# Еще больше популярных игр разных жанров
more_games = [
    {
        'title': 'Counter-Strike 2',
        'slug': 'counter-strike-2',
        'description': 'Counter-Strike 2 представляет собой крупнейший технологический скачок в истории серии, обеспечивая бесплатное обновление для всех игроков CS:GO. В игре представлены реалистичная физика, улучшенная графика и новые игровые режимы.',
        'short_description': 'Культовый тактический шутер от Valve',
        'price': 0,
        'developer': 'Valve',
        'publisher': 'Valve',
        'genre': 'ACTION',
        'platform': 'PC',
        'metacritic_score': 82,
        'release_date': date(2023, 9, 27),
        'is_available': True,
    },
    {
        'title': 'Dota 2',
        'slug': 'dota-2',
        'description': 'Dota 2 — это бесплатная MOBA-игра, в которой две команды по пять игроков сражаются на арене, пытаясь разрушить главное строение противника, Древнего. Каждый из более чем 100 уникальных героев имеет свои способности и стиль игры.',
        'short_description': 'Самая популярная MOBA в мире',
        'price': 0,
        'developer': 'Valve',
        'publisher': 'Valve',
        'genre': 'STRATEGY',
        'platform': 'PC',
        'metacritic_score': 90,
        'release_date': date(2013, 7, 9),
        'is_available': True,
    },
    {
        'title': 'Apex Legends',
        'slug': 'apex-legends',
        'description': 'Apex Legends — это бесплатный королевской битвы-шутер, в котором легендарные персонажи с мощными способностями объединяются, чтобы сражаться за славу и богатство на окраинах Предельного мира.',
        'short_description': 'Бесплатный королевской битвы от Respawn',
        'price': 0,
        'developer': 'Respawn Entertainment',
        'publisher': 'Electronic Arts',
        'genre': 'ACTION',
        'platform': 'PC, PlayStation 5, Xbox Series X/S, Nintendo Switch',
        'metacritic_score': 89,
        'release_date': date(2019, 2, 4),
        'is_available': True,
    },
    {
        'title': 'Valorant',
        'slug': 'valorant',
        'description': 'Valorant — это тактический шутер от первого лица, разработанный Riot Games. В игре представлены персонажи с уникальными способностями, которые можно использовать для победы в раундах. Точность и тактика играют ключевую роль.',
        'short_description': 'Тактический шутер от создателей League of Legends',
        'price': 0,
        'developer': 'Riot Games',
        'publisher': 'Riot Games',
        'genre': 'ACTION',
        'platform': 'PC',
        'metacritic_score': 80,
        'release_date': date(2020, 6, 2),
        'is_available': True,
    },
    {
        'title': 'League of Legends',
        'slug': 'league-of-legends',
        'description': 'League of Legends — это командная стратегическая игра, в которой две команды по пять могущественных чемпионов сражаются, чтобы разрушить базу противника. Выберите одного из более чем 140 чемпионов, чтобы совершить эпические игры.',
        'short_description': 'Самая популярная MOBA в мире с 140+ чемпионами',
        'price': 0,
        'developer': 'Riot Games',
        'publisher': 'Riot Games',
        'genre': 'STRATEGY',
        'platform': 'PC',
        'metacritic_score': 78,
        'release_date': date(2009, 10, 27),
        'is_available': True,
    },
    {
        'title': 'World of Warcraft',
        'slug': 'world-of-warcraft',
        'description': 'World of Warcraft — это массовая многопользовательская ролевая онлайн-игра, в которой игроки исследуют обширный мир Азерот, выполняют квесты, сражаются с монстрами и взаимодействуют с другими игроками.',
        'short_description': 'Культовая MMORPG от Blizzard',
        'price': 0,
        'developer': 'Blizzard Entertainment',
        'publisher': 'Blizzard Entertainment',
        'genre': 'RPG',
        'platform': 'PC, macOS',
        'metacritic_score': 93,
        'release_date': date(2004, 11, 23),
        'is_available': True,
    },
    {
        'title': 'Minecraft',
        'slug': 'minecraft',
        'description': 'Minecraft — это игра-песочница, в которой игроки могут строить и исследовать бесконечные миры, состоящие из блоков. Создавайте удивительные сооружения, выживайте в опасных условиях или просто наслаждайтесь творчеством.',
        'short_description': 'Самая продаваемая игра в истории',
        'price': 1999.99,
        'developer': 'Mojang Studios',
        'publisher': 'Xbox Game Studios',
        'genre': 'ADVENTURE',
        'platform': 'PC, PlayStation, Xbox, Nintendo Switch, Android, iOS',
        'metacritic_score': 93,
        'release_date': date(2011, 11, 18),
        'is_available': True,
    },
    {
        'title': 'Fortnite',
        'slug': 'fortnite',
        'description': 'Fortnite — это бесплатная игра королевской битвы, в которой 100 игроков сражаются за то, чтобы стать последним выжившим. Стройте укрепления, собирайте оружие и ресурсы, и побеждайте своих противников.',
        'short_description': 'Бесплатный королевской битвы с механикой строительства',
        'price': 0,
        'developer': 'Epic Games',
        'publisher': 'Epic Games',
        'genre': 'ACTION',
        'platform': 'PC, PlayStation, Xbox, Nintendo Switch, Android, iOS',
        'metacritic_score': 81,
        'release_date': date(2017, 7, 21),
        'is_available': True,
    },
    {
        'title': 'Overwatch 2',
        'slug': 'overwatch-2',
        'description': 'Overwatch 2 — это бесплатный командный шутер от первого лица, в котором игроки выбирают из разнообразного списка героев и сражаются в различных игровых режимах. Командная работа и стратегия — ключ к победе.',
        'short_description': 'Бесплатный командный шутер от Blizzard',
        'price': 0,
        'developer': 'Blizzard Entertainment',
        'publisher': 'Blizzard Entertainment',
        'genre': 'ACTION',
        'platform': 'PC, PlayStation 5, Xbox Series X/S, Nintendo Switch',
        'metacritic_score': 79,
        'release_date': date(2022, 10, 4),
        'is_available': True,
    },
    {
        'title': 'Destiny 2',
        'slug': 'destiny-2',
        'description': 'Destiny 2 — это бесплатный онлайн-шутер от первого лица с элементами MMORPG. Исследуйте солнечную систему, выполняйте миссии, участвуйте в рейдах и PvP-сражениях в постоянно развивающемся мире.',
        'short_description': 'MMO-шутер от создателей Halo',
        'price': 0,
        'developer': 'Bungie',
        'publisher': 'Bungie',
        'genre': 'ACTION',
        'platform': 'PC, PlayStation 5, Xbox Series X/S',
        'metacritic_score': 85,
        'release_date': date(2017, 9, 6),
        'is_available': True,
    },
]

# Ретро и классические игры
classic_games = [
    {
        'title': 'Half-Life 2',
        'slug': 'half-life-2',
        'description': 'Half-Life 2 — это культовый научно-фантастический шутер от первого лица, в котором вы играете за Гордона Фримена, физика, который должен сражаться с инопланетными захватчиками в постапокалиптическом мире.',
        'short_description': 'Культовый научно-фантастический шутер от Valve',
        'price': 299.99,
        'developer': 'Valve',
        'publisher': 'Valve',
        'genre': 'ACTION',
        'platform': 'PC, PlayStation 3, Xbox 360',
        'metacritic_score': 96,
        'release_date': date(2004, 11, 16),
        'is_available': True,
    },
    {
        'title': 'Portal 2',
        'slug': 'portal-2',
        'description': 'Portal 2 — это головоломка-платформер от первого лица, в которой вы используете портальную пушку для создания порталов и решения сложных головоломок. Юмор, интересный сюжет и уникальный геймплей.',
        'short_description': 'Гениальная головоломка с портальной пушкой',
        'price': 399.99,
        'developer': 'Valve',
        'publisher': 'Valve',
        'genre': 'ADVENTURE',
        'platform': 'PC, PlayStation 3, Xbox 360',
        'metacritic_score': 95,
        'release_date': date(2011, 4, 19),
        'is_available': True,
    },
    {
        'title': 'Baldur\'s Gate 3',
        'slug': 'baldurs-gate-3',
        'description': 'Соберите свою партию и вернитесь в Забытые Королевства в этой эпической RPG, полной интриг, предательства и выживания в опасном мире. Ваши выборы определяют историю в этой D&D-вдохновленной игре.',
        'short_description': 'Эпическая RPG на основе D&D 5e',
        'price': 3999.99,
        'developer': 'Larian Studios',
        'publisher': 'Larian Studios',
        'genre': 'RPG',
        'platform': 'PC, PlayStation 5, Xbox Series X/S',
        'metacritic_score': 96,
        'release_date': date(2023, 8, 3),
        'is_available': True,
    },
    {
        'title': 'Resident Evil 4 Remake',
        'slug': 'resident-evil-4-remake',
        'description': 'Переосмысление культового survival horror. Агент Леон С. Кеннеди отправляется в отдалённую европейскую деревню, чтобы спасти дочь президента, но обнаруживает ужасающую тайну.',
        'short_description': 'Ремейк культового survival horror',
        'price': 3499.99,
        'developer': 'Capcom',
        'publisher': 'Capcom',
        'genre': 'HORROR',
        'platform': 'PC, PlayStation 5, Xbox Series X/S',
        'metacritic_score': 93,
        'release_date': date(2023, 3, 24),
        'is_available': True,
    },
    {
        'title': 'Starfield',
        'slug': 'starfield',
        'description': 'Starfield — это следующее поколение ролевой игры от Bethesda Game Studios, действие которой происходит в космосе. Создайте своего персонажа и исследуйте более 1000 планет.',
        'short_description': 'Космическая RPG от создателей Skyrim',
        'price': 4999.99,
        'developer': 'Bethesda Game Studios',
        'publisher': 'Bethesda Softworks',
        'genre': 'RPG',
        'platform': 'PC, Xbox Series X/S',
        'metacritic_score': 86,
        'release_date': date(2023, 9, 6),
        'is_available': True,
    },
    {
        'title': 'Final Fantasy VII Remake',
        'slug': 'final-fantasy-vii-remake',
        'description': 'Переосмысление культовой JRPG. Присоединяйтесь к наёмнику Клауду и эко-террористической группе AVALANCHE в их борьбе против корпорации Shinra в городе Мидгар.',
        'short_description': 'Ремейк культовой японской RPG',
        'price': 3999.99,
        'developer': 'Square Enix',
        'publisher': 'Square Enix',
        'genre': 'RPG',
        'platform': 'PC, PlayStation 5, PlayStation 4',
        'metacritic_score': 87,
        'release_date': date(2020, 4, 10),
        'is_available': True,
    },
    {
        'title': 'Metro Exodus',
        'slug': 'metro-exodus',
        'description': 'Metro Exodus — это история-driven шутер от первого лица, который сочетает в себе survival horror и стелс. Сюжет основан на романах Дмитрия Глуховского.',
        'short_description': 'Постапокалиптический шутер по мотивам книг Глуховского',
        'price': 1999.99,
        'developer': '4A Games',
        'publisher': 'Deep Silver',
        'genre': 'ACTION',
        'platform': 'PC, PlayStation 5, Xbox Series X/S',
        'metacritic_score': 82,
        'release_date': date(2019, 2, 15),
        'is_available': True,
    },
    {
        'title': 'Sea of Thieves',
        'slug': 'sea-of-thieves',
        'description': 'Sea of Thieves — это приключенческая игра в открытом мире, в которой вы становитесь пиратом и вместе с друзьями исследуете океан, ищете сокровища и сражаетесь с другими пиратами.',
        'short_description': 'Пиратское приключение в открытом мире',
        'price': 1499.99,
        'developer': 'Rare',
        'publisher': 'Xbox Game Studios',
        'genre': 'ADVENTURE',
        'platform': 'PC, Xbox Series X/S, Xbox One',
        'metacritic_score': 69,
        'release_date': date(2018, 3, 20),
        'is_available': True,
    },
    {
        'title': 'Forza Horizon 5',
        'slug': 'forza-horizon-5',
        'description': 'Ваше величайшее приключение Horizon ждёт! Исследуйте живой и постоянно развивающийся открытый мир Мексики с потрясающими видами. Участвуйте в бесконечных гонках.',
        'short_description': 'Аркадные гонки в открытом мире Мексики',
        'price': 3999.99,
        'developer': 'Playground Games',
        'publisher': 'Xbox Game Studios',
        'genre': 'SPORT',
        'platform': 'PC, Xbox Series X/S, Xbox One',
        'metacritic_score': 92,
        'release_date': date(2021, 11, 9),
        'is_available': True,
    },
    {
        'title': 'FIFA 23',
        'slug': 'fifa-23',
        'description': 'FIFA 23 — последняя игра в знаменитой футбольной серии. Игра включает в себя новые механики, улучшенную графику и все официальные лиги и команды.',
        'short_description': 'Последняя часть культового футбольного симулятора',
        'price': 4999.99,
        'developer': 'EA Sports',
        'publisher': 'Electronic Arts',
        'genre': 'SPORT',
        'platform': 'PC, PlayStation 5, Xbox Series X/S, Nintendo Switch',
        'metacritic_score': 76,
        'release_date': date(2022, 9, 30),
        'is_available': True,
    },
]

# Собираем все игры вместе
all_games = aaa_games + aa_games + more_games + classic_games

print("🚀 Начинаем добавление игр в базу данных...")
print("=" * 50)

added_count = 0
updated_count = 0

for game_data in all_games:
    try:
        game, created = Game.objects.update_or_create(
            slug=game_data['slug'],
            defaults=game_data
        )
        if created:
            print(f'✅ Добавлена: {game.title} ({game.genre}) - {game.price} ₽')
            added_count += 1
        else:
            print(f'🔄 Обновлена: {game.title}')
            updated_count += 1
    except Exception as e:
        print(f'❌ Ошибка при добавлении {game_data["title"]}: {e}')

print("=" * 50)
print(f"🎮 Добавлено новых игр: {added_count}")
print(f"🔄 Обновлено существующих: {updated_count}")
print(f"📊 Всего игр в базе: {Game.objects.count()}")
print("=" * 50)

# Статистика по жанрам
print("\n📈 Статистика по жанрам:")
genres_count = Game.objects.values('genre').annotate(count=models.Count('id')).order_by('-count')
for item in genres_count:
    print(f"  {item['genre']}: {item['count']} игр")

# Статистика по ценам
free_games = Game.objects.filter(price=0).count()
paid_games = Game.objects.filter(price__gt=0).count()
print(f"\n💰 Бесплатных игр: {free_games}")
print(f"💰 Платных игр: {paid_games}")

print("\n🎉 Готово! Игры успешно добавлены в базу данных.")